version: '2'

services:

  app:
    image: quay.io/apicurio/apicurio-studio:latest-snapshot
    ports:
      - '8090:8090'

  ui:
    image: quay.io/apicurio/apicurio-studio-ui:latest-snapshot
    ports:
      - '8888:8090'
    depends_on:
      - app
